# This is a basic workflow to help you get started with Actions

name: CI-Ubuntu

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.4
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Docker compose
        run: docker-compose -f ./Resources/docker-compose.yml up -d

      - name: Test
        run: swift build --build-tests

