# This is a basic workflow to help you get started with Actions

name: CI-Ubuntu

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.3'
        
      - name: Docker compose
        run: docker-compose -f ./Resources/docker-compose.yml up -d

      - name: Test
        run: swift test -v --enable-test-discovery

