# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker setup
        uses: docker-practice/actions-setup-docker@master
        
      - name: Docker compose
        run: docker-compose -f ./Resources/docker-compose.yml up -d
        
      - name: Build
        run: swift build

      - name: Test
        run: swift test -v --skip-build 


