# This is a basic workflow to help you get started with Actions

name: Install_Docker

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - name: Run a multi-line script
        run: |
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
          eval "$(docker-machine env default)"
          docker run hello-world
          docker-machine stop default
